server:
  port: 8080

spring:
  datasource:
    username: root
    password: mxz980809
    url: jdbc:mysql://localhost:3306/seckilldemo?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://localhost:3306/seckilldemo
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 123.56.249.190

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.shane.seckilldemo.entity

